name: Pull strings

on:
    workflow_dispatch:
    schedule:
        - cron: 0 0 1 * *

jobs:
    pull:
        name: Pull strings
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Pull strings
              uses: crowdin/github-action@v1
              with:
                  config: crowdin.yml
                  download_translations: true
                  localization_branch_name: feat/translations
                  create_pull_request: true
                  pull_request_title: "chore: Sync translations"
                  pull_request_body: "Sync translations from [crowdin.com/project/revanced](https://crowdin.com/project/revanced)"
                  pull_request_base_branch_name: "dev"
                  commit_message: "chore: Sync translations"
                  github_user_name: revanced-bot
                  github_user_email: github@revanced.app
              env:
                  GITHUB_TOKEN: ${{ secrets.REPOSITORY_PUSH_ACCESS }}
                  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
