name: Push strings

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - patches/src/main/resources/addresources/values/strings.xml

jobs:
  push:
    name: Push strings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Preprocess strings
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean preprocessCrowdinStrings

      - name: Push strings
        uses: crowdin/github-action@v2
        with:
          config: crowdin.yml
          upload_sources: true
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
